AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.12

  Sample SAM Template for Appointment Bookings

Globals:
  Function:
    Timeout: 60
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  AppName:
    Type: String
    Default: Appointments
  CognitoUserEmail:
    Type: String
  TableName:
    Type: String
    Default: Appointments-Table-dev
  ClientDomains:
    Type: CommaDelimitedList
    Default: http://localhost:8080,localhost:8080

Resources:
  AppointmentApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AppName}-API-${Stage}"
      StageName: !Ref Stage
      TracingEnabled: true
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub GetUser-${Stage}
      CodeUri: handlers/get_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        AppointmentApi:
          Type: Api
          Properties:
            Path: /users
            Method: get
            RestApiId:
              Ref: AppointmentApi
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  RequestAppointment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub RequestAppointment-${Stage}
      CodeUri: handlers/request_appointment/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /appointments
            Method: post
            RestApiId:
              Ref: AppointmentApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  GetScheduleByMonth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub GetScheduleByMonth-${Stage}
      CodeUri: handlers/schedule_by_month/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /schedule/{month}
            Method: get
            RestApiId:
              Ref: AppointmentApi
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  ConfirmAppointment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ConfirmAppointment-${Stage}
      CodeUri: handlers/confirm_appointment/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        AppointmentApi:
          Type: Api
          Properties:
            Path: /appointments/{id}/confirm
            Method: patch
            RestApiId:
              Ref: AppointmentApi
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  CancelAppointment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub CancelAppointment-${Stage}
      CodeUri: handlers/cancel_appointment/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        AppointmentApi:
          Type: Api
          Properties:
            Path: /appointments/{id}/cancel
            Method: patch
            RestApiId:
              Ref: AppointmentApi
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  CreateClient:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub CreateClient-${Stage}
      CodeUri: handlers/create_client/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /clients
            Method: post
            RestApiId:
              Ref: AppointmentApi
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  GetClient:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub GetClient-${Stage}
      CodeUri: handlers/get_client/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /clients/{email}
            Method: get
            RestApiId:
              Ref: AppointmentApi
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  ListClients:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ListClients-${Stage}
      CodeUri: handlers/list_clients/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /clients
            Method: get
            RestApiId:
              Ref: AppointmentApi
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services

  Services:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: services/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "GSI1PK"
          AttributeType: "S"
        - AttributeName: "GSI1SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: 'GSI1'
          KeySchema:
          - AttributeName: "GSI1PK"
            KeyType: "HASH"
          - AttributeName: "GSI1SK"
            KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AppName}-UserPool-${Stage}"
      Policies:
        PasswordPolicy:
          MinimumLength: 6
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: false
        - Name: "family_name"
          Required: true
          Mutable: true
        - Name: "given_name"
          Required: true
          Mutable: true
        - Name: "nickname"
          Required: true
          Mutable: true

  PostConfirmation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub PostConfirmation-${Stage}
      CodeUri: handlers/auth_workflow/post_confirmation
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          STAGE: !Ref Stage
          TABLE_NAME: !Ref TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Layers:
      - !Ref Services
      Events:
        CognitoTrigger:
          Type: Cognito
          Properties:
            Trigger: PostConfirmation
            UserPool: !Ref CognitoUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "${AppName}-UserPoolClient-${Stage}"
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs: !Ref ClientDomains
      LogoutURLs: !Ref ClientDomains
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub appointments-${AWS::AccountId}-${Stage}
      UserPoolId: !Ref CognitoUserPool

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  AppointmentApi:
    Description: "API Gateway endpoint URL for Prod stage for Create Appointment Function"
    Value: !Sub "https://${AppointmentApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
  UserPoolId:
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub ${AppName}:UserPoolId
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
  AuthUrl:
    Description: "URL for authentication"
    Value: !Sub https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com
